@baseUrl = http://localhost:8000
@username = admin
@password = admin
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjg0MjA5NTA1LCJpYXQiOjE2ODQyMDU5MDUsImp0aSI6Ijg2MmYzNmE2YzkyMjRjMGNhYWExYjE0NDFkOGM5MGViIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJhZG1pbiJ9.rUWGfBZ6IGUD7XBZ9OCaJZLllMx91oFm4p6BtceWjAs

###
GET {{baseUrl}}/users/?page=1
Content-Type: application/json
Authorization: Bearer {{access_token}}


###
DELETE {{baseUrl}}/users/2/
Content-Type: application/json
Authorization: Bearer {{access_token}}


###
GET {{baseUrl}}/users/1
Content-Type: application/json
Authorization: Bearer {{access_token}}


###
POST {{baseUrl}}/authenticate
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "admin"
}
