@baseUrl = http://localhost:8000
@username = admin
@password = admin
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjgyOTYxMTQ3LCJpYXQiOjE2ODI5NTc1NDcsImp0aSI6IjNiOWIyYjI3ODljOTQ0Mjc5NjA2MTUxMmE3Y2RlZjkzIiwidXNlcl9pZCI6NzksInVzZXJuYW1lIjoic2VlZDMifQ.o8KaL2zD-Rt-ozV3lJm8Ddyvz3MA32QfcBMp9OYtjds

###
GET {{baseUrl}}/users/?page=1
Content-Type: application/json
Authorization: Bearer {{access_token}}


###
DELETE {{baseUrl}}/users/2/
Content-Type: application/json
Authorization: Bearer {{access_token}}


###
GET {{baseUrl}}/users/1
Content-Type: application/json
Authorization: Bearer {{access_token}}


###
POST {{baseUrl}}/authenticate
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "admin"
}
